### ISSUE TITLE
Link [Edit and Contribute] (https://github.com/japaric/eulermark.rs/edit/master/006.md) is 404

### ISSUE THREAD

**Issue by anaran** [japaric-archived/eulermark.rs#1]
See these links:

https://github.com/japaric/eulermark.rs/edit/master/006.md

  referenced from

http://japaric.github.io/eulermark.rs/006.html

**Comment by japaric** [comment]
This repository has been deprecated in favor of [`euler_criterion.rs`](https://github.com/japaric/euler_criterion.rs/tree/master/problems/001) (*) and won't receive further updates.

(*) euler_criterion.rs doesn't yet have a static site like eulermark.rs does, but that's on the [TODO list](https://github.com/japaric/euler_criterion.rs/issues/5).
